'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace T501713


    Partial Public Class WebForm1

        ''' <summary>
        ''' ASPxButton1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxButton1 As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' Master property.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated property.
        ''' </remarks>
        Public Shadows ReadOnly Property Master() As T501713.Root
            Get
                Return (DirectCast(MyBase.Master, T501713.Root))
            End Get
        End Property
    End Class
End Namespace
